version: '2'
services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
     - postgres
    links:
      - postgres:postgres
    entrypoint: ["mix phx.server"]

  postgres:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
